POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "firstname": "Omar",
  "lastname": "Griggio",
  "email": "omar@test3.ch",
  "passwordHash": "123456"
}

###

POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "omar@test3.ch",
  "passwordHash": "123456"
}

###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzAxNTE3NCwiZXhwIjoxNzgzMDMzMTc0fQ.yT3jPtFN3Sa0Lnu-vzM77JaY75_zBBKYdjh9wNqWtcQ

###

GET http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o


###

POST http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o
Content-Type: application/json

{
  "nom": "Boesiger",
  "prenom": "Charle",
  "email": "omar.griggio@gmail.com",
  "code_client": "BSI",
  "societe": "Boesiger AG",
  "telephone": ""
}

###

DELETE  http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o
Content-Type: application/json

{
  "nom": "Boesiger",
  "prenom": "Charle",
  "email": "omar.griggio@gmail.com",
  "code_client": "BSI",
  "societe": "Boesiger AG",
  "telephone": ""
}

###
POST http://localhost:3000/fournisseur
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o
Content-Type: application/json

{
  "code_fournisseur" : "SELLITA",
  "societe": "selltia",
  "adresse": "rte de chaumont 20",
  "categorie": "horlogerie"
}

###
GET http://localhost:3000/facture
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o
Content-Type: application/json

###
GET http://localhost:3000/facture-complete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o
Content-Type: application/json

###
GET http://localhost:3000/facture-complete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o
Content-Type: application/json