@token = PASTE_FRESH_TOKEN_FROM_AUTH.HTTP_HERE

GET http://localhost:3000/adresse
Authorization: Bearer {{token}}

###

POST http://localhost:3000/adresse
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id_client": 1,
  "rue": "Rue de la Gare 1",
  "npa": "2000",
  "ville": "Neuchâtel",
  "pays": "Suisse"
}
