GET http://localhost:3000/chantier

###

POST http://localhost:3000/chantier
Content-Type: application/json

{
  "id_client": 1,
  "id_type_chantier": 1,
  "nom": "Réparation de porte de garage",
  "remarque": null,
  "adresse_identique_client": false,
  "rue": "Rue de la gare 2",
  "npa": "2500",
  "ville": "Lausanne",
  "pays": "Suisse"
}

###

DELETE http://localhost:3000/chantier/1
