@token = PASTE_FRESH_TOKEN_FROM_AUTH.HTTP_HERE

GET http://localhost:3000/client
Authorization: Bearer {{token}}

###

GET http://localhost:3000/client/1
Authorization: Bearer {{token}}

###

POST http://localhost:3000/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "client_number": "BSI",
  "type": "PROFESSIONAL",
  "company_name": "Boesiger AG",
  "vat_number": null,
  "last_name": "Boesiger",
  "first_name": "Charle",
  "title": "Monsieur",
  "email": "omar.griggio@gmail.com",
  "phone": "",
  "note": null
}

###

PATCH http://localhost:3000/client/1/archive
Authorization: Bearer {{token}}
