@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsInJvbGUiOiJBRE1JTiIsImlkX2VudHJlcHJpc2UiOjEsImlhdCI6MTc4Mzk1NzU0MywiZXhwIjoxNzgzOTc1NTQzfQ.cIR62mHMPIm0w-IH6q3CVAQDpOgGDN34IvE3EOEfE7c

GET http://localhost:3000/client
Authorization: Bearer {{token}}

###

GET http://localhost:3000/client/1
Authorization: Bearer {{token}}

###

POST http://localhost:3000/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "num_client": "BSI",
  "type": "PROFESSIONNEL",
  "societe": "Boesiger AG",
  "tva": null,
  "nom": "Boesiger",
  "prenom": "Charle",
  "civilite": "Monsieur",
  "email": "omar.griggio@gmail.com",
  "telephone": "",
  "remarque": null
}

###

DELETE  http://localhost:3000/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "num_client": "BSI"
}
