@token = PASTE_FRESH_TOKEN_FROM_AUTH.HTTP_HERE

GET http://localhost:3000/document
Authorization: Bearer {{token}}

###

GET http://localhost:3000/document?type=QUOTE
Authorization: Bearer {{token}}

###

POST http://localhost:3000/document
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "client_id": 1,
  "parent_document_id": null,
  "type": "QUOTE",
  "number": "QUOTE-2026-001",
  "date": "2026-07-09",
  "discount": 0,
  "status": "DRAFT"
}
