@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsInJvbGUiOiJBRE1JTiIsImlkX2VudHJlcHJpc2UiOjEsImlhdCI6MTc4Mzk1NzU0MywiZXhwIjoxNzgzOTc1NTQzfQ.cIR62mHMPIm0w-IH6q3CVAQDpOgGDN34IvE3EOEfE7c

GET http://localhost:3000/document
Authorization: Bearer {{token}}

###

GET http://localhost:3000/document?type=OFFRE
Authorization: Bearer {{token}}

###

POST http://localhost:3000/document
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id_client": 1,
  "id_document_parent": null,
  "type": "OFFRE",
  "numero": "OFFRE-2026-001",
  "date": "2026-07-09",
  "montant_ht": 1000,
  "montant_ttc": 1077,
  "rabais": 0,
  "statut": "en_attente"
}
