@token = PASTE_FRESH_TOKEN_FROM_AUTH.HTTP_HERE

GET http://localhost:3000/document-complete
Authorization: Bearer {{token}}
Content-Type: application/json

###

GET http://localhost:3000/document-complete?type=INVOICE
Authorization: Bearer {{token}}
Content-Type: application/json

###

GET http://localhost:3000/document-complete/1
Authorization: Bearer {{token}}
Content-Type: application/json
