GET http://localhost:3000/entreprise

###

GET http://localhost:3000/entreprise/1

###

POST http://localhost:3000/entreprise
Content-Type: application/json

{
  "nom_entreprise": "DEDONNOSTYLE",
  "email": "dedonnostyle@gmail.com",
  "telephone": "+41799549936",
  "rue": "Rue de boujean 37",
  "npa": "2502",
  "ville": "Biel/Bienne",
  "pays": "Suisse",
  "logo": "CheminDuLogo"
}

###

PUT http://localhost:3000/entreprise/1
Content-Type: application/json

{
  "nom_entreprise": "DE DONNO STYLE SARL",
  "email": "dedonnostyle@gmail.com",
  "telephone": "+41799549936",
  "iban": "CH8500790016247615012",
  "rue": "Rue de boujean 37",
  "npa": "2502",
  "ville": "Biel/Bienne",
  "pays": "Suisse",
  "logo": "CheminDuLogo"
}
