GET http://localhost:3000/offre-materiel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o

###

POST http://localhost:3000/offre-materiel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoib21hckB0ZXN0My5jaCIsImlhdCI6MTc4MzUxOTk4MSwiZXhwIjoxNzgzNTM3OTgxfQ.7U7poXqcOCPUZEXh3v2fTvjznur7rZjZ6RU16yTI03o
Content-Type: application/json

{
  "id_offre": 1,
  "id_tarifs_materiel": 1,
  "pos": 1,
  "ref_materiel": "REF-001",
  "libelle_materiel": "Vis horlogère",
  "quantite": 10,
  "tarif": 5.5,
  "rabais": 0
}
