@token = PASTE_FRESH_TOKEN_FROM_AUTH.HTTP_HERE

GET http://localhost:3000/ressource
Authorization: Bearer {{token}}

###

GET http://localhost:3000/ressource?type=MATERIEL
Authorization: Bearer {{token}}

###

GET http://localhost:3000/ressource?type=MAIN-OEUVRE
Authorization: Bearer {{token}}

###

GET http://localhost:3000/ressource?type=SOUS-TRAITANCE
Authorization: Bearer {{token}}

###

GET http://localhost:3000/ressource?type=DIVERS
Authorization: Bearer {{token}}
