@token = PASTE_FRESH_TOKEN_FROM_AUTH.HTTP_HERE

POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "id_entreprise": 1,
  "role":"ADMIN",
  "firstname": "Omar",
  "lastname": "Griggio",
  "email": "omar@test3.ch",
  "passwordHash": "123456"
}

###

DELETE http://localhost:3000/user/2 HTTP/1.1
Authorization: Bearer {{token}}

###

GET http://localhost:3000/user
Authorization: Bearer {{token}}
